# Generated by Django 4.2.2 on 2023-07-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30, null=True, verbose_name='email'),
        ),
    ]
